config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/new'
  get 'users/index', to: 'users#index'
  post 'users', to: 'users#create'
  get 'users/:id', to: 'users#show'
  get 'home/index'
  get 'home/call_job'
  get 'home/call_job_synchronized'
  root to: 'home#index'
  # matchメソッドと:viaオプションを使うと、複数のHTTPメソッドに同時にマッチするルーティングを作成
  match 'getpost', to: 'home#getpost', via: %i[get post]
  resources :job_statuses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# アプリケーションレコード設定
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job_status.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: job_statuses
#
#  id         :bigint           not null, primary key
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class JobStatus < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  age        :integer
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Banken
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# ホームコントローラー設定
class HomeController < ApplicationController
  def index; end

  def getpost
    # binding.pry
    # ソースコードの中に記述することで、binding.pryという文字列が存在する部分でRailsの処理を止めることができる
    # ppはpよりも読みやすくオブジェクトを表示
    # pp params

    # Strong Parameters → Web上から受けつけたパラメータが、本当に安全なデータかどうかを検証した上で、取得するための仕組み
    # フォームなどによって送られてきた情報を取得するメソッド
    # permitメソッドはparamsで取得したパラメータに対し保存の許可処理を行うメソッド
    # to_hメソッドは、配列をハッシュに変換するメソッド
    permit_parameters = params.permit(:key1, :key2, :key3, :name_input_text, keywords: [:keyword]).to_h

    pp permit_parameters[:key1]
    pp permit_parameters[:key2]
    pp permit_parameters[:key3]
    pp permit_parameters[:name_input_text]
    permit_parameters[:keywords].each do |keyword|
      pp keyword[:keyword]
    end
  end

  def call_job
    SampleJob.perform_later
  end

  # def call_job_synchronized
  #   SampleJob.perform_now
  # end
end

app/controllers/job_statuses_controller.rb
# frozen_string_literal: true

# ジョブステータスコントローラー設定
class JobStatusesController < ApplicationController
  before_action :set_job_status, only: %i[show edit update destroy]

  # GET /job_statuses or /job_statuses.json
  def index
    @job_statuses = JobStatus.all
  end

  # GET /job_statuses/1 or /job_statuses/1.json
  def show; end

  # GET /job_statuses/new
  def new
    @job_status = JobStatus.new
  end

  # GET /job_statuses/1/edit
  def edit; end

  # POST /job_statuses or /job_statuses.json
  def create
    @job_status = JobStatus.new(job_status_params)

    respond_to do |format|
      if @job_status.save
        format.html { redirect_to job_status_url(@job_status), notice: 'Job status was successfully created.' }
        format.json { render :show, status: :created, location: @job_status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_statuses/1 or /job_statuses/1.json
  def update
    respond_to do |format|
      if @job_status.update(job_status_params)
        format.html { redirect_to job_status_url(@job_status), notice: 'Job status was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_statuses/1 or /job_statuses/1.json
  def destroy
    @job_status.destroy

    respond_to do |format|
      format.html { redirect_to job_statuses_url, notice: 'Job status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_job_status
    @job_status = JobStatus.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def job_status_params
    params.require(:job_status).permit(:status)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# ユーザーコントローラー設定
class UsersController < ApplicationController
  def new; end

  def create
    permit_parameters = params.require(:user).permit(:name, :age)
    user = User.new(permit_parameters)
    render 'new' if user.save
    pp permit_parameters[:name]
    pp permit_parameters[:age]
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    authorize!
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# アプリケーションヘルパー設定
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# ホームヘルパー設定
module HomeHelper
end

app/helpers/job_statuses_helper.rb
# frozen_string_literal: true

# ジョブステータスヘルパー設定
module JobStatusesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# ユーザーヘルパー設定
module UsersHelper
end

app/views/home/get_post.html.erb
<h1>Home#getpost</h1>
<p>Find me in app/views/home/getpost.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

input_text: <input type="text" id="input_text" name="name_input_text" maxlength="8" size="10">
<br>
keywords: <input type="text" group='keyword' maxlength="8" size="10">
<input type="text" group='keyword' maxlength="8" size="10">
<input type="text" group='keyword' maxlength="8" size="10">
<br>
<button type="button" id="button_get">Fetch API : GET</button> | 
<button type="button" id="button_post">Fetch API : POST</button>
<script>
  const button_get = document.getElementById('button_get');
  button_get.addEventListener('click', function() {
    fetch('/getpost', {
      method: 'GET'
    })
    // thenメソッドは処理が成功した場合に返す
    .then(function(response) {
      // response.status:HTTPレスポンスステータスコードを返す
      // response.statusText:HTTPコードが200はOK、100はContinue、404はNot found
      const response_message = response.status + ':' + response.statusText
      console.log(response_message);
      window.alert('response_message=' + response_message);
    });
  });

  const button_post = document.getElementById('button_post');
  button_post.addEventListener('click', function() {
    const post_data = {
      key1: "data1",
      key2: "data2",
      key3: 3
    };

    const input_text = document.getElementById('input_text');
    post_data[input_text.name] = input_text.value;

    // input要素のgroup属性がkeywordの静的なNodeListを返す
    // Nodeはドキュメント自身で、要素やテキスト、コメントなどがある
    const keyword_nodes = document.querySelectorAll("input[group='keyword']");
    const keyword_data = [];
    for (let keyword_node of keyword_nodes) {
      const keyword = {keyword: keyword_node.value};
      keyword_data.push(keyword);
    }
    post_data['keywords'] = keyword_data;

    fetch('/getpost', {
      method: 'POST',
      // 同じオリジンの場合は認証情報を送る
      // オリジンとはURLのプロトコル、ドメイン、ポートで定義
      credentials: 'same-origin',
      headers: {
        // リクエスト時にメディアタイプを指定する役割(今回はJSONファイル)
        'Content-Type': 'application/json',
        // Request headerにX-CSRF-Tokenを付与
        'X-CSRF-Token': getCsrfToken()
      },
      // JavaScript のオブジェクトや値を JSON 文字列に変換
      body: JSON.stringify(post_data),
    })
    .then(function(response) {
      if (!response.ok) {
        console.error('response.ok:', response.ok);
        console.error('response.status:', response.status);
        console.error('response.statusText:', response.statusText);
        // throw文はコールスタック内の最初の catch ブロックに制御を移す
        // throw new Errorでエラーオブジェクトを生成
        throw new Error(response.statusText)
      }
      const response_message = response.status + ':' + response.statusText
      console.log(response_message);
      window.alert('response_message=' + response_message);
    });
    .catch(function(error) {
      console.error('エラーが発生しました', error)
    })
  });

  const getCsrfToken = () => {
    const metas = document.getElementsByTagName('meta');
    for (let meta of metas) {
      // getAttribute()は要素の指定された属性の値を返す
      if (meta.getAttribute('name') === 'csrf-token') {
        console.log('csrf-token:', meta.getAttribute('content'));
        return meta.getAttribute('content');
      }
    }
    return '';
  }
</script>

app/views/job_statuses/_form.html.erb
<%# form_withを使わずに、htmlタグでフォームを実装した為、form_with のコードをコメントアウトしました。%>
<%
=begin
%>

<%= form_with(model: job_status) do |form| %>
  <% if job_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_status.errors.count, "error") %> prohibited this job_status from being saved:</h2>

      <ul>
        <% job_status.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%
=end
%>

<form action="/job_statuses" method="post">
  <% if job_status.errors.any? %>
    <div id="error_explanation">
      <%# pluralizeメソッドは英語の単数や複数を出し分ける %>
      <h2><%= pluralize(job_status.errors.count, "error") %> prohibited this job_status from being saved:</h2>

      <ul>
        <% job_status.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <input type="hidden" name="authenticity_token" value="RarC_7_4hHswkRJGvNbhjnHwvyB3uQK9340ZsYRKtFnHEE7hdtkpovi7zTeR2EITZCDRxsOnfioVFnov5pgIEg">
  <div class="field">
    <label for="job_status_status">Status</label>
    <input type="number" name="job_status[status]" id="job_status_status">
  </div>
  <div class="actions">
    <%# data-disable-with属性でクリックした後に、「Create Job Status」という文言にし、クリック禁止にできる(ダブルクリック防止) %>
    <input type="submit" name="commit" value="Create Job status" data-disable-with="Create Job status">
  </div>
</form>

app/views/job_statuses/edit.html.erb
<h1>Editing Job Status</h1>

<%= render 'form', job_status: @job_status %>

<%= link_to 'Show', @job_status %> |
<%= link_to 'Back', job_statuses_path %>

app/views/job_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Job Statuses</h1>

<button type="button" id="reload" onclick="reload()">reload</button>
<button type="button" id="calljob" onclick="calljob()">call job</button>
<%# <button type="button" id="calljob_synchronized">call job synchronized</button> %>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_statuses.each do |job_status| %>
      <tr>
        <td><%= job_status.status %></td>
        <td><%= link_to 'Show', job_status %></td>
        <td><%= link_to 'Edit', edit_job_status_path(job_status) %></td>
        <td><%= link_to 'Destroy', job_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job Status', new_job_status_path %>

<script>
  function reload() {
    window.location.reload();
    console.log("リロード完了")
  }

  function calljob() {
    fetch('/home/call_job', {
      method: 'GET'
    });
    console.log("calljob完了")
  }

  // var reload = document.getElementById('calljob_synchronized');
  // reload.addEventListener('click', function() {
  //   // fetch()メソッドは、「非同期通信という方法で、サーバ上にある欲しいデータを取得できる」
  //   fetch('/home/call_job_synchronized', {
  //     method: 'GET'
  //   });
  // });
</script>

app/views/job_statuses/new.html.erb
<h1>New Job Status</h1>

<%= render 'form', job_status: @job_status %>

<%= link_to 'Back', job_statuses_path %>

app/views/job_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @job_status.status %>
</p>

<%= link_to 'Edit', edit_job_status_path(@job_status) %> |
<%= link_to 'Back', job_statuses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<ul>
	<% @users.each do |user| %>
		<li>
			<div>
				<p>ユーザー名：<%= user.name %></p>
				<p>年齢：<%= user.age %></p>
			</div>
		</li>
	<% end %>
</ul>

app/views/users/new.html.erb
<h1>Users新規作成</h1>

<label for="name">ユーザー名</label>
<input type="text" id="user_name" name="name" maxlength="8" placeholder="ユーザー名を入力して下さい">
<br>

<label for="age">年齢</label>
<input type="number" id="user_age" name="age" maxlength="8" placeholder="年齢を入力して下さい">
<br>

<button type="button" id="user_post">Fetch API : POST</button>

<script>
  const user_post = document.getElementById('user_post');
  user_post.addEventListener('click', function(){
    const user_data = {
      name: "",
      age: "",
    };

    const user_name = document.getElementById('user_name');
    user_data.name = user_name.value;
    const user_age = document.getElementById('user_age');
    user_data.age = user_age.value;

    fetch('/users', {
      method: 'POST',
      credentials: 'same-origin',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-Token': getCsrfToken()
      },
      body: JSON.stringify(user_data),
    })
    .then(function(response) {
      if (!response.ok) {
        console.error('response.ok:', response.ok);
        console.error('response.status:', response.status);
        console.error('response.statusText:', response.statusText);
        throw new Error(response.statusText)
      }
      const response_message = response.status + ':' + response.statusText
      console.log(response_message);
      window.alert('response_message=' + response_message);
    })
    .catch(function(error) {
      console.error('エラーが発生しました', error)
    })
  });

  const getCsrfToken = () => {
    const metas = document.getElementsByTagName('meta');
    for (let meta of metas) {
      // getAttribute()は要素の指定された属性の値を返す
      if (meta.getAttribute('name') === 'csrf-token') {
        console.log('csrf-token:', meta.getAttribute('content'));
        return meta.getAttribute('content');
      }
    }
    return '';
  }
</script>

app/views/users/show.html.erb
<h1><%= @user.name %>さんのマイページ</h1>

<p>年齢：<%= @user.age %></p>